### ISSUE TITLE
Selections works not properly in Safari v13 with shadow Dom 

### ISSUE THREAD

**Issue by tkless** [arsnebula/polymer-quill#9]
Hi,

I have already tried out some WYSIWYG editors, that should working with ShadowDom in my Project.
So I find your polymer-quill, you have adapted from quill.js. It works fine in Chrome and FieFox but in Safari jumps the cursor at the beginning of the line when you want to make the certain word edited.

I find this polyfill for Safari that probably solves this Problem.
[https://github.com/GoogleChromeLabs/shadow-selection-polyfill](https://github.com/GoogleChromeLabs/shadow-selection-polyfill)

Would you be able to incorporate this polyfill in your quill?

Best wishes,
Tea

**Comment by chrismbeckett** [comment]
This project is extremely out of date and is no longer supported. It was created as a demonstration for the QuillJS team. My personal opinion is also that Polyfills should be transparent to the components that rely on them. Many projects that once included Polyfills have removed them since it really should be a decision made by the host website whether they want to include polyfills, browser support, etc, rather than individual components.
